### ISSUE TITLE
ModUpdater version

### ISSUE THREAD

**Issue by srnyx** [gbl/InfiniteVillagerTrading#1]
I'm getting this waring on start-up on Fabric 1.16.5 server:
```
[01:26:27] [main/WARN]: Warnings were found! 
 - Mod 'InfiniteVillagerTrading' (infinitevillagertrading) recommends version 1.1.7 or later of mod modupdater, which is missing!
         - You must install version 1.1.7 or later of modupdater.
```

**Comment by gbl** [comment]
Yes. That's because the mod supports ModUpdater, so you can install it, and it'll give you a message when there's a newer version of InfiniteVillagerTrading available. If you don't install ModUpdater, you won't get that info. The mod will work normally though, that's why it says "recommends" but doesn't stop the launch.

**Comment by srnyx** [comment]
> Yes. That's because the mod supports ModUpdater, so you can install it, and it'll give you a message when there's a newer version of InfiniteVillagerTrading available. If you don't install ModUpdater, you won't get that info. The mod will work normally though, that's why it says "recommends" but doesn't stop the launch.
> 
> 

Isn't ModUpdater only for clients though, and not servers?

**Comment by gbl** [comment]
No. On a server, you don't get the ModMenu GUI, obviously, but it has a /modupdater command.
